name: Build and Attach Stable ZIP

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # build minified files based on package.json
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build minified files
        run: npm run build

      # copy package.public.json as package.json to dist
      - name: Copy minimal package.json
        run: cp package.public.json dist/package.json

      # create zip archive of dist and demo folder
      - name: Create stable ZIP
        run: |
          mkdir release-zip
          cp dist/vbook.min.css release-zip/
          cp dist/vbook.min.js release-zip/
          cp -r demo release-zip/
          zip -r vbook-latest.zip release-zip
          
      # Upload ZIP to GitHub Release
      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v2
        with:
          files: vbook-stable.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 8️⃣ (Optional) Commit built files to main
      # Falls du möchtest, dass dist/ auch im Repo landet:
      #- name: Commit and push dist to main
      #    if: ${{ false }} # auf true ändern, wenn du das möchtest
      #    run: |
    #      git config --global user.name "GitHub Action"
    #      git config --global user.email "actions@github.com"
    #      git add dist/
    #      git commit -m "Build: update dist files for $GITHUB_REF [skip ci]" || echo "No changes"
    #      git push origin main
